In [1]:
# Load packages
import pandas as pd
import numpy  as np
from collections import Counter
import os

In [2]:
#File names and base path.
base_datapath = 'C:\\Users\\sapmn3\\Database\\OFFCORSS\\data\\OFFCORSS_Ventas'

file_list = ['Franquicias_2019',
             'Franquicias_2020',
            ]

ventas_franquicias = []

for cur_file in file_list:
    file_source = cur_file.split('_')[0]
    print(cur_file)
    cur_path = os.path.join(base_datapath, cur_file + '.csv')
    cur_data = pd.read_csv(cur_path, encoding = 'latin1', delimiter = ';')
        
    cur_data['Source'] = file_source
        
    if len(ventas_franquicias) == 0:
        ventas_franquicias = cur_data
    else:
        ventas_franquicias = pd.concat([ventas_franquicias, cur_data], axis=0)

Franquicias_2019

C:\Users\sapmn3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (23,44,45) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

Franquicias_2020

C:\Users\sapmn3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (23) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
#File names and base path.
base_datapath = 'C:\\Users\\sapmn3\\Database\\OFFCORSS\\data\\OFFCORSS_Ventas\\TiendasPropias'

file_list = ['Enero_2019','Febrero_2019','Marzo_2019','Abril_2019',
             'Mayo_2019','Junio_2019','Julio_2019','Agosto_2019',
             'Septiembre_2019','Octubre_2019','Noviembre_2019','Diciembre_2019',
             'Enero_2020','Febrero_2020','Marzo_2020','Abril_2020',
             'Mayo_2020','Junio_2020','Julio_2020','Agosto_2020',
            ]

ventas_tiendas = []

for cur_file in file_list:
    file_source = cur_file.split('_')[0]
    print(cur_file)
    cur_path = os.path.join(base_datapath, cur_file + '.csv')
    cur_data = pd.read_csv(cur_path, encoding = 'latin1', delimiter = ';')
        
    cur_data['Source'] = file_source
        
    if len(ventas_tiendas) == 0:
        ventas_tiendas = cur_data
    else:
        ventas_tiendas = pd.concat([ventas_tiendas, cur_data], axis=0)

Enero_2019
Febrero_2019
Marzo_2019
Abril_2019
Mayo_2019
Junio_2019
Julio_2019
Agosto_2019
Septiembre_2019
Octubre_2019
Noviembre_2019
Diciembre_2019
Enero_2020
Febrero_2020
Marzo_2020
Abril_2020
Mayo_2020
Junio_2020
Julio_2020
Agosto_2020

In [4]:
base_datapath = 'C:\\Users\\sapmn3\\Database\\OFFCORSS\\data\\OFFCORSS_Ventas'

file_list = ['TV_2019',
             'TV_2020'
            ]

ventas_virtual = []

for cur_file in file_list:
    file_source = cur_file.split('_')[0]
    print(cur_file)
    cur_path = os.path.join(base_datapath, cur_file + '.csv')
    cur_data = pd.read_csv(cur_path, encoding = 'latin1', delimiter = ';')
        
    cur_data['Source'] = 'tVirtual'
        
    if len(ventas_virtual) == 0:
        ventas_virtual = cur_data
    else:
        ventas_virtual = pd.concat([ventas_virtual, cur_data], axis=0)

TV_2019

C:\Users\sapmn3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (21,52) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

TV_2020

C:\Users\sapmn3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (52) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
(ventas_tiendas.columns)

Index(['C. Clase Fact.', 'D. Clase Fact.', '# Factura', '# Pedido', 'Sociedad',
       'C. Org. Vtas', 'D. Org. Vtas', 'C. Canal', 'D. Canal', 'C. Centro',
       'D. Centro', ' Ciudad ', 'C. Of. Vtas', 'D. Of. Vtas', 'F. Factura',
       'Año Factura', 'Mes Factura', 'Año-Mes Factura', 'Día Factura',
       'Día Semana', 'H. Factura', 'Hora Factura', 'Cod. Cliente', 'Cédula',
       'Nombre Cliente', 'Posición', 'C. Material', 'D. Material',
       'valor Matriz', 'Talla', 'Color', 'PLU', 'Unidad', 'contador',
       'Cantidad', 'Moneda', 'Costo Unitario', 'Vlr. Bruto', '% Desc.',
       'Vlr. Desc.', 'Vlr. Neto', 'Vlr. Iva', 'Vlr. Total',
       'Vlr. Dto Ccial VMI', 'C. Condición', 'D. Condición', 'C. Usuario',
       'C. Vendedor', 'N. Vendedor', 'Marca', 'Tipo de Negocio', 'Destino',
       'Año de Venta', 'Mes de Venta', 'Edad', 'Género', 'Sublínea',
       'Grupo de Artículo', 'Tipo de Artículo', 'Tipo de Tejido',
       'Tipo de Referencia', 'País de Orígen', 'Saldo', 'Clase',
       'Concepto Diseño', 'Colección', 'Source'],
      dtype='object')

In [6]:
ventas_franquicias.columns

Index(['C. Clase Fact.', 'D. Clase Fact.', '# Factura', '# Pedido', 'Sociedad',
       'C. Org. Vtas', 'D. Org. Vtas', 'C. Canal', 'D. Canal', 'C. Centro',
       'D. Centro', ' Ciudad ', 'C. Of. Vtas', 'D. Of. Vtas', 'F. Factura',
       'Año Factura', 'Mes Factura', 'Año-Mes Factura', 'Día Factura',
       'Día Semana', 'H. Factura', 'Hora Factura', 'Cod. Cliente', 'Cédula',
       'Nombre Cliente', 'Posición', 'C. Material', 'D. Material',
       'valor Matriz', 'Talla', 'Color', 'PLU', 'Unidad', 'contador',
       'Cantidad', 'Moneda', 'Costo Unitario', 'Vlr. Bruto', '% Desc.',
       'Vlr. Desc.', 'Vlr. Neto', 'Vlr. Iva', 'Vlr. Total',
       'Vlr. Dto Ccial VMI', 'C. Condición', 'D. Condición', 'C. Usuario',
       'C. Vendedor', 'N. Vendedor', 'Marca', 'Tipo de Negocio', 'Destino',
       'Año de Venta', 'Mes de Venta', 'Edad', 'Género', 'Sublínea',
       'Grupo de Artículo', 'Tipo de Artículo', 'Tipo de Tejido',
       'Tipo de Referencia', 'País de Orígen', 'Saldo', 'Clase',
       'Concepto Diseño', 'Colección', 'Source'],
      dtype='object')

In [7]:
ventas_virtual.columns

Index(['Nro. Pedido', 'Estado', 'C. Clase Pedido', 'N. Clase Pedido',
       'Est. Entrega', 'Est. Pedido', 'Est. Rechazo', 'Nro. Ped. C.',
       'Via de pago', 'Nro. P. Original', 'F. P. Original', 'Campaña VD',
       'Zona VD', 'C. Org. Vtas.', 'D. Org. Vtas.', 'C. Canal D.',
       'D. Canal D.', 'F. Pedido', 'F. Creación', 'H. Creación',
       'F. Preferente', 'F. Fin Validez', 'Usuario Pedido', 'C. Solicitante',
       'N. Solicitante', 'C. Destinatario', 'N. Destinatario',
       'Población Destinatario', 'C. Tienda', 'N. Tienda', 'Pos. Ped',
       'Pos. Rep', 'Unidad Vta', 'Material', 'Beneficio dia sin IVA',
       'Desc. Material', 'Vlr Matriz', 'Talla', 'Color', 'EAN', 'PLU',
       'M. Rechazo Reparto', 'M. Rechazo Posición', 'C. Pedido', 'C. Reserva',
       'C. O. Entrega', 'C. F. Entrega', 'C. Factura', 'C. Pendiente',
       'Moneda', 'Vlr. Unitario', 'Vlr. Pedido', 'Vlr. Reserva',
       'Vlr. Entrega', 'Vlr. Factura', 'Marca', 'Tipo de Negocio', 'Destino',
       'Año de Venta', 'Mes de Venta', 'Edad', 'Género', 'Sublínea',
       'Grupo de Artículo', 'Tipo de Artículo', 'Tipo de Tejido',
       'Tipo de Referencia', 'País de Orígen', 'Saldo', 'Clase',
       'Concepto Diseño', 'Colección', 'Email Asesor', 'Nombre Asesor',
       'Clase de Condición', 'Canal', 'Nombre Canal', 'Source'],
      dtype='object')

In [8]:
# Select required columns
data_tiendas_selected = ventas_tiendas[['# Factura',
                                    '# Pedido',
                                    'D. Canal',
                                    ' Ciudad ',
                                    'F. Factura',
                                    'D. Material',
                                    'Vlr. Neto',
                                    'Vlr. Iva',
                                    'Vlr. Total',
                                    'Tipo de Referencia',
                                    'Colección',
                                    'Source'
                                    ]]

data_tiendas_selected.head()

,# Factura,# Pedido,D. Canal,Ciudad,F. Factura,D. Material,Vlr. Neto,Vlr. Iva,Vlr. Total,Tipo de Referencia,Colección,Source
0,90410576,60407921,Tiendas Propias,CALI,2/01/2019,ZAPATOS COSIDOS,"-41.933,00","-7.967,00","-49.900,00",PRENDA EXTERIOR,8379.0,Enero
1,90410577,60407922,Outlets,MEDELLIN,2/01/2019,SANDALIAS EN SINTETICO,"-58.739,00","-11.160,00","-69.900,00",ACCESORIO,8446.0,Enero
2,90410577,60407922,Outlets,MEDELLIN,2/01/2019,TENIS EN CUERO CON TROQUEL,"-45.294,00","-8.606,00","-53.900,00",PRENDA EXTERIOR,7887.0,Enero
3,90410578,60407926,Tiendas Propias,CALI,2/01/2019,TENIS,"-71.345,00","-13.556,00","-84.900,00",PRENDA EXTERIOR,8378.0,Enero
4,90410579,60407928,Tiendas Propias,MEDELLIN,1/01/2019,OVERALL EN TEJIDO PLANO CON CARGADERAS G,"-75.546,00","-14.354,00","-89.900,00",PRENDA EXTERIOR,8812.0,Enero

In [9]:
# Select required columns
data_franquicias_selected = ventas_franquicias[['# Factura',
                                    '# Pedido',
                                    'D. Canal',
                                    ' Ciudad ',
                                    'F. Factura',
                                    'D. Material',
                                    'Vlr. Neto',
                                    'Vlr. Iva',
                                    'Vlr. Total',
                                    'Tipo de Referencia',
                                    'Colección',
                                    'Source'
                                    ]]

data_franquicias_selected.head()

,# Factura,# Pedido,D. Canal,Ciudad,F. Factura,D. Material,Vlr. Neto,Vlr. Iva,Vlr. Total,Tipo de Referencia,Colección,Source
0,90410574,60407896,Tiendas Franquicias,OCAÑA,2/01/2019,CAMISETA MANGA CORTA EN TEJIDO DE PUNTO,"-26.807,00","-5.093,00","-31.900,00",PRENDA EXTERIOR,8383.0,Franquicias
1,90410575,60407918,Tiendas Franquicias,SOGAMOSO,1/01/2019,OVERALL EN TEJIDO PLANO CON CARGADERAS G,"-75.546,00","-14.354,00","-89.900,00",PRENDA EXTERIOR,8812.0,Franquicias
2,90410580,60407930,Tiendas Franquicias,PALMIRA,1/01/2019,VESTIDO MS EN TEJIDO PLANO,"-58.739,00","-11.160,00","-69.900,00",PRENDA EXTERIOR,8875.0,Franquicias
3,90410581,60407933,Tiendas Franquicias,TUNJA,2/01/2019,TENIS EN SINTETICO CON CORDONES,"-75.546,00","-14.354,00","-89.900,00",PRENDA EXTERIOR,8513.0,Franquicias
4,90410582,60407934,Tiendas Franquicias,PALMIRA,1/01/2019,CAMISA ML CUELLO NERU EN TEJIDO PLANO,"-58.739,00","-11.160,00","-69.900,00",PRENDA EXTERIOR,8374.0,Franquicias

In [10]:
# Select required columns
data_virtual_selected = ventas_virtual[['Nro. Pedido',
                                'F. Pedido',
                                'Población Destinatario',
                                'Desc. Material',
                                'Vlr. Factura',
                                'Colección',
                                'Tipo de Referencia',
                                'Tipo de Artículo',
                                'Concepto Diseño',
                                'Source'
                                 ]]

data_virtual_selected.head()

,Nro. Pedido,F. Pedido,Población Destinatario,Desc. Material,Vlr. Factura,Colección,Tipo de Referencia,Tipo de Artículo,Concepto Diseño,Source
0,66021827,14/12/2019,NaN,"CAMISA MANGA CORTA EN TEJIDO PLANO, LLEV","63.782,00",9047.0,PRENDA EXTERIOR,CAMISA MANGA CORTA,SPECIAL OCCASIONS,tVirtual
1,66021827,14/12/2019,NaN,"CAMISA MANGA CORTA EN TEJIDO PLANO, LLEV","63.782,00",9047.0,PRENDA EXTERIOR,CAMISA MANGA CORTA,SPECIAL OCCASIONS,tVirtual
2,66021827,14/12/2019,NaN,CAMISETA MANGA LARGA EN TEJIDO DE PUNTO,"58.739,00",8977.0,PRENDA EXTERIOR,CAMISETA MANGA LARGA,PLAYA,tVirtual
3,66021827,14/12/2019,NaN,CAMISETA MANGA LARGA EN TEJIDO DE PUNTO,"58.815,00",9238.0,PRENDA EXTERIOR,CAMISETA MANGA LARGA,PLAYA,tVirtual
4,66021827,14/12/2019,NaN,BODY MC EN TEJIDO DE PUNTO,"55.454,00",9443.0,PRENDA EXTERIOR,BODY MANGA CORTA,ROAD TO ALASKA,tVirtual

In [11]:
# Save processed files
save_datapath = 'C:\\Users\\sapmn3\\Database\\OFFCORSS\\data\\data_clean'

save_file = 'offcorss_ventas_tiendas'
save_path = os.path.join(save_datapath, save_file + '.csv')

data_tiendas_selected.to_csv(save_path, encoding='utf-8-sig')
    
save_file = 'offcorss_ventas_franquicias'
save_path = os.path.join(save_datapath, save_file + '.csv')

data_franquicias_selected.to_csv(save_path, encoding='utf-8-sig')
    
save_file = 'offcorss_ventas_virtual'
save_path = os.path.join(save_datapath, save_file + '.csv')

data_virtual_selected.to_csv(save_path, encoding='utf-8-sig')

In [14]:
data_tiendas_selected['D. Material'].unique()

array(['ZAPATOS COSIDOS', 'SANDALIAS EN SINTETICO',
       'TENIS EN CUERO CON TROQUEL', ..., 'CHANCLAS EN CUERO CON DRIL',
       'BERMUDA EN TEJIDO PLANO CON ELASTICO', 'TULA PARA COLOREAR'],
      dtype=object)

In [16]:
data_virtual_selected['Tipo de Artículo'].unique()

array(['CAMISA MANGA CORTA', 'CAMISETA MANGA LARGA', 'BODY MANGA CORTA',
       'BIKINI', 'CAMISETA MANGA CORTA', 'TENIS', 'CONJUNTO LARGO',
       'PANTALON', 'DENIM', 'CHALECO', 'CAMISETA POLO',
       'CUIDADO PERSONAL', 'CONJUNTO CORTO', 'BERMUDA', 'SUDADERA',
       'CAMISETA MANGA SISA', 'SHORT', 'CAMISA MANGA SISA',
       'OVERALL CORTO', 'SWEATER', 'CAMISA MANGA LARGA',
       'PIJAMA ENTERIZO', 'SANDALIA', 'BUZO', 'VESTIDO MANGA CORTA',
       'GORRO', 'LEGGINGS', nan, 'ZAPATO', 'OVERALL LARGO', 'BOTAS',
       'PIJAMA ML-PL', 'TOALLA', 'ZAPATOS PRECAMINADOR', 'ENTERIZO CORTO',
       'PIJAMA SET', 'SET', 'CHAQUETA', 'GAFAS', 'VESTIDO MANGA LARGA',
       'VESTIDO MANGA SISA', 'ZAPATOS COSIDOS', 'PIJAMA MC-PL',
       'VESTIDO ENTERO', 'PANTALONETA', 'CARGADERA', 'CORBATA',
       'ENTERIZO LARGO', 'TOALLA PLAYERA', 'COBIJA SENCILLA',
       'BODY MANGA SISA', 'CAÑA LARGA', 'TANKINI', 'COBIJA SEMIDOBLE',
       'BODY MANGA LARGA', 'PIECITO', 'RELOJ', 'BALETA', 'MINIFALDA',
       'PAÑOLETA', 'TABLERO', 'BODY', 'BOXER', 'SOMBRERO',
       'CONJUNTO SUDADERA', 'PANTY CLASICO', 'PUÑO DOBLADO', 'TOP CORTO',
       'BOLSITA', 'TOBILLERA', 'SALIDA DE BAÑO', 'PIJAMA MC-PC',
       'FALDA LARGA', 'FALDA-PANTALON', 'BABITAS', 'CAÑA CORTA', 'CORREA',
       'KIMONO', 'JUMPER', 'CAPA', 'OTROS', 'GORRO DE BAÑO', 'VESTIDO',
       'CUADERNO', 'DIADEMA', 'BUFANDA', 'BALACA', 'BABERO', 'LONCHERA',
       'MEDIA ANTALON', 'PIJAMA MS-PC', 'TUTU', 'BOLSO', 'MORRAL',
       'BOMBACHO', 'CACHUCHA', 'PAÑALERA', 'ARETAS', 'CAMISA MANGA 3/4',
       'ANTIFAZ', 'AGUA DE LINOS', 'CARTUCHERA', 'CAMISETA',
       'PANTY RETRO', 'JABON', 'HEBILLAS', 'TERMO', 'SLEEPING', 'COLLAR',
       'PRENDEDOR', 'MEDIAS', 'JUGUETE', 'STICKERS', 'GABAN', 'CHOLITOS',
       'TENDIDO CAMA SENC', 'TAPETE CARGADOR', 'BILLETERA',
       'JUEGO SABANAS SENC', 'FULAR', 'SABANA RESORTADA', 'OREJERAS',
       'CREMA', 'LOCION', 'ANTIBACTERIAL', 'VISERA', 'FALDA'],
      dtype=object)

In [39]:
products_ls = list(np.unique(
             ['CAMISA','CAMISETA','BODY','BIKINI','TENIS','CONJUNTO','PANTALON','DENIM', 'CHALECO',
              'BERMUDA', 'SUDADERA','SHORT','OVERALL', 'SWEATER','PIJAMA','ENTERIZO', 'SANDALIA', 'BUZO', 
              'VESTIDO','GORRO', 'LEGGINGS','ZAPATO', 'OVERALL', 'BOTAS', 'TOALLA','SET','CHAQUETA', 'GAFAS',
              'PANTALONETA', 'CARGADERA', 'CORBATA','COBIJA','CAÑA','TANKINI','PIECITO', 'RELOJ', 'BALETA','MINIFALDA',
              'PAÑOLETA', 'TABLERO', 'BODY', 'BOXER', 'SOMBRERO','PANTY', 'PUÑO', 'TOP',
              'BOLSITA', 'TOBILLERA', 'BAÑO','FALDA', 'FALDA', 'BABITAS', 'CORREA',
              'KIMONO', 'JUMPER', 'CAPA', 'GORRO', 'VESTIDO','CUADERNO', 'DIADEMA', 'BUFANDA', 'BALACA', 'BABERO', 'LONCHERA',
              'MEDIA','TUTU', 'BOLSO', 'MORRAL','BOMBACHO', 'CACHUCHA', 'PAÑALERA', 'ARETAS',
              'ANTIFAZ', 'LINOS', 'CARTUCHERA','JABON', 'HEBILLAS', 'TERMO', 'SLEEPING', 'COLLAR',
              'PRENDEDOR', 'MEDIAS', 'JUGUETE', 'STICKERS', 'GABAN', 'CHOLITOS', 'TENDIDO', 'TAPETE', 'BILLETERA',
              'FULAR','OREJERAS','CREMA', 'LOCION', 'ANTIBACTERIAL', 'VISERA', 'FALDA'
              ]))
products_ls = [word.lower() for word in products_ls]
products_ls

['antibacterial',
 'antifaz',
 'aretas',
 'babero',
 'babitas',
 'balaca',
 'baleta',
 'baño',
 'bermuda',
 'bikini',
 'billetera',
 'body',
 'bolsita',
 'bolso',
 'bombacho',
 'botas',
 'boxer',
 'bufanda',
 'buzo',
 'cachucha',
 'camisa',
 'camiseta',
 'capa',
 'cargadera',
 'cartuchera',
 'caña',
 'chaleco',
 'chaqueta',
 'cholitos',
 'cobija',
 'collar',
 'conjunto',
 'corbata',
 'correa',
 'crema',
 'cuaderno',
 'denim',
 'diadema',
 'enterizo',
 'falda',
 'fular',
 'gaban',
 'gafas',
 'gorro',
 'hebillas',
 'jabon',
 'juguete',
 'jumper',
 'kimono',
 'leggings',
 'linos',
 'locion',
 'lonchera',
 'media',
 'medias',
 'minifalda',
 'morral',
 'orejeras',
 'overall',
 'pantalon',
 'pantaloneta',
 'panty',
 'pañalera',
 'pañoleta',
 'piecito',
 'pijama',
 'prendedor',
 'puño',
 'reloj',
 'sandalia',
 'set',
 'short',
 'sleeping',
 'sombrero',
 'stickers',
 'sudadera',
 'sweater',
 'tablero',
 'tankini',
 'tapete',
 'tendido',
 'tenis',
 'termo',
 'toalla',
 'tobillera',
 'top',
 'tutu',
 'vestido',
 'visera',
 'zapato']

In [40]:
# Save processed files
save_datapath = 'C:\\Users\\sapmn3\\Database\\OFFCORSS\\data\\data_clean'

save_file = 'offcorss_products'
save_path = os.path.join(save_datapath, save_file + '.csv')

products_df = {'products': products_ls}
products_df = pd.DataFrame(data = products_df)
products_df.to_csv(save_path, encoding='utf-8-sig')

In [45]:
B_in_A_bool = np.in1d(products_ls, 'botas', assume_unique=True)
B_in_A_bool

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])